### ISSUE TITLE
can't upload using folders:upload

### ISSUE THREAD

**Issue by ZhyeYin** [box/boxcli#231]
- [X ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I use our company's custom certificate by setting NODE_EXTRA_CA_CERTS before running box CLI command. 
I can upload a file from a local folder to box using files:upload -p but somehow I can't do folders:upload. 
folders:upload command does create a folder with same name as a given local folder but fails to upload the contents of the local folder.  The local folder is located in a server's own scratch space (not in a network drive). 

### Steps to Reproduce
My colleague and I tested 2 different linux servers we owned. We were able to reproduce at least in our site. 

### Expected Behavior
I was expecting the files are uploaded. 

### Error Message, Including Stack Trace
yin@nsk1neuron:~/bin$ /home/yin/bin/box folders:upload -v /scratch_nobackup/tmp_zy3 -p XXXXXXXXX
  box:@box/cli:hooks:init done +0ms
  box init version: @oclif/command@1.5.5 argv: [ 'folders:upload', '-v', '/scratch_nobackup/tmp_zy3', '-p', 'XXXXXXXX' ] +0ms
  box-cli:init Initializing Box CLI +0ms
  box-cli:init Loaded settings {
  box-cli:init   boxReportsFolderPath: '/projects/projects_crt/Box/Reports',
  box-cli:init   boxReportsFileFormat: 'txt',
  box-cli:init   boxDownloadsFolderPath: '/projects/projects_crt/Box',
  box-cli:init   outputJson: false,
  box-cli:init   enableProxy: true,
  box-cli:init   proxy: {
  box-cli:init     url: 'http://XXXXXXXX.com:8080',
  box-cli:init     username: null,
  box-cli:init     password: null
  box-cli:init   }
  box-cli:init } +2ms
  box-cli:init Using environment default {
  box-cli:init   clientId: 'vlowbuizlkuqjyxuh6nyfqgovj0qtt2q',
  box-cli:init   enterpriseId: '186603',
  box-cli:init   boxConfigFilePath: '/projects/projects_crt/tools/box_cli2/186603_zlz1xje8_config.json',
  box-cli:init   hasInLinePrivateKey: true,
  box-cli:init   privateKeyPath: null,
  box-cli:init   name: 'default',
  box-cli:init   defaultAsUserId: null,
  box-cli:init   useDefaultAsUser: false,
  box-cli:init   cacheTokens: true
  box-cli:init } +5ms
  box-cli:init Initialized client from environment config +24ms
  box-cli:execute Starting execution command: folders:upload argv: [ '-v', '/scratch_nobackup/tmp_zy3', '-p', 'XXXXXXXXX' ] +0ms
  box-cli:execute Running framework error handler +1m
  box-cli:execute Handling re-thrown error in base command handler +238ms
BoxCLIError: Could not upload file /scratch_nobackup/tmp_zy3/TCT0.11830.2.1.1552901371.389430_NI_180mA_a-1.4317_-020ms.image.adf.0256_None_wMC_P01.med.sdcopen
Caused by: Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/projects/projects_crt/tools/box_cli2/node_modules/@box/cli/node_modules/request/request.js:816:19)
    at Object.onceWrapper (node:events:482:28)
    at ClientRequest.emit (node:events:376:20)
    at TLSSocket.emitRequestTimeout (node:_http_client:787:9)
    at Object.onceWrapper (node:events:482:28)
    at TLSSocket.emit (node:events:376:20)
    at TLSSocket.Socket._onTimeout (node:net:481:8)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)

### Versions Used
Box CLI:@box/cli/2.8.0 linux-x64 node-v15.4.0
Operating System: Ubuntu 16.04.4

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by swfree** [comment]
Hi @ZhyeYin thank you for filing this issue! I was able to reproduce the issue you're seeing as well, so I've created a ticket in our backlog to prioritize & fix this.

**Comment by packj** [comment]
Glad to hear this will be prioritized.  Looking forward to using box CLI to upload folders

**Comment by wapowell** [comment]
I'm having the same issue using boxcli for a mac.  Any update on this?

**Comment by swfree** [comment]
We've released a fix for this issue in our latest release: https://github.com/box/boxcli/releases/tag/v2.9.0.

**Comment by ZhyeYin** [comment]
I downloaded the latest release but still can't use folders:upload capability. See the version of box CLI I used and the error output. 

/scratch_nobackup$  /home/yin/bin/box_2.9.0 help
Official command line interface for the Box API

VERSION
  @box/cli/2.9.0 linux-x64 node-v15.5.1

Error output:
BoxCLIError: Could not upload file tmp_jed3/small_file.txt
Caused by: Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/projects/projects_crt/tools/boxcli-master/node_modules/request/request.js:816:19)
    at Object.onceWrapper (node:events:482:28)
    at ClientRequest.emit (node:events:376:20)
    at TLSSocket.emitRequestTimeout (node:_http_client:787:9)
    at Object.onceWrapper (node:events:482:28)
    at TLSSocket.emit (node:events:376:20)
    at TLSSocket.Socket._onTimeout (node:net:481:8)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)

**Comment by shalev123d** [comment]
Hi, can confirm we're also having this issue - 
`

Caused by: Error: ESOCKETTIMEDOUT
--
2821 | at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@box/cli/node_modules/request/request.js:816:19)
2822 | at Object.onceWrapper (events.js:420:28)
2823 | at ClientRequest.emit (events.js:314:20)
2824 | at TLSSocket.emitRequestTimeout (_http_client.js:715:9)
2825 | at Object.onceWrapper (events.js:420:28)
2826 | at TLSSocket.emit (events.js:326:22)
2827 | at TLSSocket.Socket._onTimeout (net.js:483:8)
2828 | at listOnTimeout (internal/timers.js:554:17)
2829 | at processTimers (internal/timers.js:497:7)

`
